### ISSUE TITLE
Issues after Stellar Protocol 13 upgrade

### ISSUE THREAD

**Issue by yuriescl** [stellar-deprecated/transfer-server-validator#141]
These errors appeared after the Stellar Protocol upgrade on 2020-06-18:
![screenshot_12](https://user-images.githubusercontent.com/26092447/85050911-33648a00-b16d-11ea-8e33-2678ab63c6cc.png)

Any ideas if this is an issue with the Anchor?

**Comment by msfeldstein** [comment]
@yuriescl can you update the stellar sdk on your anchor?  We updated it on our reference implementation and our tests continue to pass

**Comment by yuriescl** [comment]
We're using the latest Python SDK: https://github.com/StellarCN/py-stellar-base/releases/tag/2.6.0

**Comment by yuriescl** [comment]
All our tests were passing yesterday using Python SDK v2.5.2

**Comment by yuriescl** [comment]
> All our tests were passing yesterday using Python SDK v2.5.2

I meant our tests using the Anchor Validator and Connector Demo.

At the moment all our internal automated tests work normally (they're written using the same Python SDK v2.6.0). This includes SEP10, SEP24 and SEP6

**Comment by JakeUrban** [comment]
I'm not sure whats wrong but I know our reference server is using the Python SDK version 2.4 and is passing all tests.

**Comment by yuriescl** [comment]
Just reverted the Anchor to Python SDK v2.5.3, all green on the Anchor Validator.
The issues appear only when using Python SDK v2.6.0.

**Comment by msfeldstein** [comment]
that's concerning thanks for finding that.  Maybe we can try to update polaris to 2.6 and see if we break the same way @JakeUrban ?

**Comment by JakeUrban** [comment]
There are breaking changes related to M-addresses (CAP-23) in 2.5 and up so it would take some time to adjust the code. I'm assuming @yuriescl is aware of these breaking changes since their internal tests are passing.

**Comment by msfeldstein** [comment]
ah so we expect 2.6 to break until CAP-23 is rolled out?  Should we ask the maintainers to roll back the 2.6 version which looks live on PyPI? https://pypi.org/project/stellar-sdk/

**Comment by JakeUrban** [comment]
[Python SDK 2.6](https://github.com/StellarCN/py-stellar-base/releases/tag/2.6.0) uses V1 transactions by default, which would change the way the XDR is decoded. Is it possible our JS library is failing to decode the XDR?

**Comment by overcat** [comment]
Sorry for this happening, I have already [rolled back](https://pypi.org/project/stellar-sdk/2.6.0/) this version on PyPi. Will take a closer look at this issue tomorrow. 😭

**Comment by tomerweller** [comment]
I don't think there's a need to rollback. It seems like the problem was the outdated JS sdk on the validator.

**Comment by JakeUrban** [comment]
@overcat This may not be an issue with 2.6. I think the JS SDK version we were using couldn't decode V1 transactions.

**Comment by yuriescl** [comment]
Is it safe to assume Python SDK v2.6.0 can be used in production right now?

**Comment by tomerweller** [comment]
@yuriescl yes, it should work now. Sorry for the inconvenience.
