### ISSUE TITLE
Fix SEP31 tests after protocol update

### ISSUE THREAD

**Issue by JakeUrban** [stellar-deprecated/transfer-server-validator#161]
@abuiles changed the URLs used but the validator hadn't been updated with prior changes to the protocol. For example, the `transactions` tests don't send `sender_id` or `receiver_id`. Update the SEP-31 tests so they're up to spec.

**Comment by abuiles** [comment]
@jacekn I think we need to add a step and if SEP12 related fields are required, then we need to add a new flow to negotiate those values. The original implementation took the path where those fields are not required.
