### ISSUE TITLE
`/customer` doesn't return proper schema for existing customer for testanchor.stellar.org

### ISSUE THREAD

**Issue by lydiat** [stellar-deprecated/transfer-server-validator#168]
When running SEP-31 tests for our test anchor domain, a test fails with

```
Expected: Any<String>
Received: "184"
    at Object.<anonymous> (/usr/src/app/cases-SEP31/customer.test.js:93:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

http://anchor-validator.stellar.org/?home_domain=testanchor.stellar.org&mainnet=false&project=SEP31

(also it would be nice if the page title reflected the SEP chosen)

**Comment by Zagan202** [comment]
This was resolved here https://github.com/stellar/transfer-server-validator/commit/39e602faef2b94a99668f27c6cabd2aa67f32663
