### ISSUE TITLE
Unnecessary Optional Memo Fields

### ISSUE THREAD

**Issue by Zagan202** [stellar-deprecated/transfer-server-validator#172]
Check if deposit transactions have unnecessary fields such as "withdraw_memo". Also, there is the same field (deposit_memo) in the withdraw transaction.

**Comment by Zagan202** [comment]
From SEP-24
>deposit_memo : (optional) This is the memo (if any) used to transfer the asset to the to Stellar address

>withdraw_memo : Memo used when the user transferred to withdraw_anchor_account. Assigned null if the withdraw is not ready to receive payment, for example if KYC is not completed.

What an example response currently looks like.
```
{
  transaction: {
    id: "2f9b46d1-188e-4f81-9c58-283bac5ed252",
    kind: "deposit",
    status: "incomplete",
    status_eta: null,
    amount_in: null,
    amount_out: null,
    amount_fee: null,
    started_at: "2020-09-14T19:43:03.301649Z",
    completed_at: null,
    stellar_transaction_id: null,
    external_transaction_id: null,
    more_info_url: "https://testanchor.stellar.org/sep24/transaction/more_info?id=2f9b46d1-188e-4f81-9c58-283bac5ed252",
    refunded: false,
    message: "incomplete",
    to: "GCQJX6WGG7SSFU2RBO5QANTFXY7C5GTTFJDCBAAO42JCCFIMZ7PEBURP",
    from: null,
    deposit_memo_type: "hash",
    deposit_memo: null,
  },
}
```

**Comment by Zagan202** [comment]
Should we remove these fields from the response if they are null?
@JakeUrban

**Comment by JakeUrban** [comment]
No, the attributes should always be the same for the same API call. `null` values are perfectly fine.

**Comment by JakeUrban** [comment]
I saw Lobstr mentioned this to ClickPesa, but thats not up-to-spec. It would be alright to omit `deposit_memo` from a `POST /withdraw` request, but `deposit_memo` should always be included on `POST /deposit` requests regardless of its value.

**Comment by Zagan202** [comment]
Action Item:
Write a `transfer-server-validator/cases-SEP24/transaction.test.js` test to check and ensure that `POST /deposit requests`'s responses do not contain fields that can be found in `POST /withdraw requests`'s responses
