### ISSUE TITLE
Fix Transaction and Transactions tests failing due to claimable_balance_id added to the schema

### ISSUE THREAD

**Issue by Zagan202** [stellar-deprecated/transfer-server-validator#195]
When the reference server is used as the Domain the transaction and transactions test
`has the correct object schema for an existing deposit transaction` transaction.test.js
`Transactions return proper formatted transactions list - Transactions return proper formatted transactions list ` 

`claimable_balance_id` is an optional parameter that the validator's test should be able to handle.

### Error found 

`should NOT have additional properties, but found 'claimable_balance_id'`

**Comment by dustpan28645** [comment]
Nice

**Comment by JakeUrban** [comment]
Resolved with https://github.com/stellar/transfer-server-validator/commit/061b1538534669d1d18be2c3af37fc3a32e19506
