### ISSUE TITLE
Publish docker image to registry

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/transfer-server-validator#34]
Right now the image is published to msfeldstein/transfer-server-validator, it should be in @stellar/transfer-server-validator and we should add one-line run commands to the readme

**Comment by msfeldstein** [comment]
It'd be great to auto-deploy this from master

**Comment by JakeUrban** [comment]
Got CircleCI to build and push the image every time something is pushed/merged to master. Will work as soon as stellar/ops#192 is resolved.
