### ISSUE TITLE
Add link to test source codes on github from the UI 

### ISSUE THREAD

**Issue by gpg4** [stellar-deprecated/transfer-server-validator#51]
Having the stacktrace is nice, but sometimes it does not provide the full information about what is being tested.

![image](https://user-images.githubusercontent.com/984711/75554171-df615880-5a4a-11ea-84d0-87c50b9a3f60.png)

It would be great to add the link to the github file to view the full source code of the test.

I would suggest adding links to the headers of the test sections.

SEP-10 test section could have a link in the header to this file:
https://github.com/stellar/transfer-server-validator/blob/master/cases/sep10.test.js

These links probably would not change often, so can be hardcoded.

**Comment by msfeldstein** [comment]
just pushed a PR for this

**Comment by msfeldstein** [comment]
https://github.com/stellar/transfer-server-validator/pull/62
