### ISSUE TITLE
Order of tests cases is not fixed

### ISSUE THREAD

**Issue by gpg4** [stellar-deprecated/transfer-server-validator#52]
We've noticed that currently the order of the test cases can change with each re-fresh of the page.

I think it makes sense to make this order fixed.

The tests of toml should probably come first, since if toml file is not configured correctly, most of the other tests will fail.
This can make it difficult for the anchor to understand the cause of the problem - as might not be obvious that the failure of the first tests is caused by misconfigured toml file:
![image](https://user-images.githubusercontent.com/984711/75554892-459aab00-5a4c-11ea-9f9f-67fc128f4b5d.png)

I would suggest to lock the order of the tests and have them listed in the following order:
- toml
- info
- sep-10
- deposit
- transactions
- transaction
- fee.optional

**Comment by JakeUrban** [comment]
I agree, we'll just have to have a hard-coded list since directories don't have inherent file order.

**Comment by little-wave** [comment]
#57 related
