### ISSUE TITLE
Improve validation for home domain input

### ISSUE THREAD

**Issue by gpg4** [stellar-deprecated/transfer-server-validator#55]
Looks like there's currently no post validation for the home domain.

The tool works fine if user enters: "https://anchorusd.com".

However, to allow for a better UX let's make sure that the following inputs would also be treated as valid:
- anchorusd.com
- https://anchorusd.com/

Currently this does not seem to be the case.

- https:// prefix is required by sep standard. So if protocol scheme is omitted, the tool can add https:// automatically 
- the trailing "/" can be safely removed automatically if entered by the user

**Comment by msfeldstein** [comment]
we should make anchorusd.com work too.
