### ISSUE TITLE
/transactions endpoint tests

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/transfer-server-validator#6]
implmement all /transactions endpoint tests here
https://docs.google.com/spreadsheets/d/1LzETPUzfX_7gKjVQhbMnKHy0yimRRcm0jU8oYBZD3WA/edit#gid=0

**Comment by JakeUrban** [comment]
Lobstr added a good set of the tests mentioned in the google sheet but there are a couple remaining. I'll add these.
