### ISSUE TITLE
Remove expectation of SEP10 network_passphrase

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/transfer-server-validator#65]
SEP10 has an optional `network_passphrase`that we were expecting to always be populated, but we should not expect it to be there, and definitely not assert that it's there.

remove this assertion: https://github.com/stellar/transfer-server-validator/blob/master/cases/sep10.test.js#L95

Replace this with StellarSdk.NEtworks.TESTNET (eventually an env var) https://github.com/stellar/transfer-server-validator/blob/master/cases/sep10.test.js#L103

**Comment by JakeUrban** [comment]
Removed
