### ISSUE TITLE
Support all field types for interactive flow

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/transfer-server-validator#84]
Currently we only support text fields for auto-complete via the `test-value` attribute. This is because we  use [sendKeys](https://github.com/stellar/transfer-server-validator/blob/master/cases/util/interactive.js#L73) instead of setting the value directly.  We should figure out how to use `.value=` instead so that it works for a wider range of field types.  Specifically, Select (ChoiceField), and most likely Radio fields, don't work

**Comment by vitchor** [comment]
If the dropdown field already has a valid option selected as default, this should work.
